#!/bin/bash

docker run -p 27018:27017 --name test_mongo -d mongo

docker run \
  --net host \
  --name test_authentification \
  -e AUTHENTIFICATION_API_PORT=4000 \
  -e AUTHENTIFICATION_DATABASE_CONNEXION_STRING='mongodb://127.0.0.1:27018' \
  -d \
  authentification
docker run \
  --net host \
  --name test_profile \
  -e PROFILE_API_PORT='4001' \
  -e PROFILE_DATABASE_CONNEXION_STRING='mongodb://127.0.0.1:27018' \
  -e PROFILE_AUTHENTIFICATION_URL='http://localhost:4000' \
  -d \
  profile

